version: '3.7'
services:
  tax-down-db:
    container_name: tax-down-db
    image: 'mongo:7.0.8'
    restart: on-failure
    env_file: ./.env
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - ./data/tax-down-db:/data/db:rw
